# Generated by Django 5.0.6 on 2024-05-20 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_pedido', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado_pedido',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='TipoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_promocion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_promocion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasenia', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.especialidad')),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField()),
                ('moneda', models.FloatField()),
                ('conversion', models.FloatField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.cliente')),
                ('id_estado_pedido', models.ForeignKey(db_column='id_estado_pedido', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.estadopedido')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_upc', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.categoriaproducto')),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.especialidad')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('id_pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.pedido')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.producto')),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.usuario'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vendedor', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('id_especialidad', models.ForeignKey(db_column='id_especialidad', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.especialidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.usuario')),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora_envio', models.DateTimeField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.cliente')),
                ('id_vendedor', models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.vendedor')),
            ],
            options={
                'db_table': 'mensaje',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.producto')),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.sucursal')),
            ],
            options={
                'db_table': 'inventario',
                'unique_together': {('id_sucursal', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.producto')),
                ('id_tipo_promocion', models.ForeignKey(db_column='id_tipo_promocion', on_delete=django.db.models.deletion.CASCADE, to='ferremax_app.tipopromocion')),
            ],
            options={
                'db_table': 'promocion',
                'unique_together': {('id_producto', 'id_tipo_promocion')},
            },
        ),
    ]
